//go:build wangshu_p4 && !wangshu_p3

package crescent

import (
	"github.com/Liam0205/wangshu/internal/arena"
	"github.com/Liam0205/wangshu/internal/gibbous/jit"

	// Blank-import the PJ10 per-opcode translator sub-package so its
	// init() registers the PJ10 hook with jit.Compiler. With this in
	// place, the compiler's SupportsAllOpcodes / Compile fall through to
	// the per-op translator for shapes PJ7 rejects (constant tuples with
	// N > 1 returns today; arithmetic / control flow / table ops in
	// PJ10b+). Removing this import reverts to pure PJ7 behaviour.
	_ "github.com/Liam0205/wangshu/internal/gibbous/jit/peroptranslator"
)

// newStateArena builds the State's main arena -- under the wangshu_p4 build
// it uses a pure Go heap backing
// (`docs/design/p4-method-jit/05-system-pipeline.md` §3.5 "under the P4 build
// the backing switches back to a pure Go heap, without going through the
// wazero memory intermediary, but the offset-addressing protocol is the same
// as P3").
//
// **Fundamental difference from P3**: under the P3 build the arena backing
// adopts wazero linear memory (`internal/crescent/arena_p3.go`); under the P4
// build the arena lives on the Go heap, and the native code generated by P4
// reads/writes the arena's `[]byte` start pointer directly via unsafe.Pointer
// (05 §3.5). GCRef offset addressing has identical semantics under both
// backing forms, which is exactly how the 02 §1.6 discipline ("per-arch means
// splitting to this architecture, not rewriting") is honored in the backing
// dimension.
//
// arenaOpts: wangshu.Options.{InitialArenaBytes,MaxArenaBytes} are passed
// through (zero values fall back inside arena.New to the default 64 KiB / 2
// GiB, staying consistent with the same constants as P3).
//
// Returns (arena, cleanup, p3env): cleanup defaults to nil (under the P4 build
// the arena is a pure Go heap, reclaimed naturally by GC, no manual cleanup
// needed); p3env is always nil (P4 does not introduce a wazero dependency,
// aligning with the P3 field-reuse discipline).
func newStateArena(arenaOpts arena.Options) (*arena.Arena, func(), any) {
	return arena.New(arenaOpts), nil, nil
}

// wireP3 is a no-op under the wangshu_p4 build (P3+P4 are mutually exclusive
// build tags; this build does not enable P3).
//
// Follows the user's ruling on the "mutually exclusive build tag protocol"
// (main-assistant decision) + `06-backends.md` §1 + `07-p3-retirement.md` §5
// retiring P3 by default. `wangshu_p3` and `wangshu_p4` may not be enabled at
// the same time -- mutually exclusive tags are the simplest approach at the
// PJ0 stage, aligning with P3's single-field `b.p3` injection; after P3 is
// retired in PJ11 the whole group of wireP3 files can be deleted and wireP4
// takes over entirely.
func (st *State) wireP3() {}

// wireP4 constructs the P4 Compiler and injects it into the bridge (follows
// `docs/design/p4-method-jit/00-overview.md` §4 PJ0 row + the same
// arena_p3.go::wireP3 injection-protocol template as P3).
//
// **PJ7 wired up** (2026-06-25):
//  1. construct jit.Compiler;
//  2. inject into the bridge (b.SetP3Compiler);
//  3. **inject P4HostState** (c.SetHostState(st)) -- after the mmap segment
//     executes, P4's p4Code.Run calls host.DoReturn to finish popping the
//     frame + moving results (because in P4's simplified form the mmap
//     segment does not call host helpers internally, the Go side must tear
//     down the frame -- follows the "Go-side frame teardown" option in the
//     `docs/design/p4-method-jit/05-system-pipeline.md` §4 trampoline
//     three-exit protocol).
//
// **At the PJ7 stage SupportsAllOpcodes has opened** the single-BB whitelist
// "LOADK A K(0); RETURN A 1" -- the bridge main path goes through
// considerPromotion → P4 Compile → installGibbous to promote a Proto of that
// shape; crescent.doCall detects TierGibbous → enterGibbous → takes the P4
// path via p4Code.Run.
func (st *State) wireP4() {
	c := jit.New()
	if c == nil {
		return
	}
	// PJ7 wired up: inject *State as P4HostState (*State implements
	// DoReturn, already present in gibbous_host.go, shared with P3).
	// **per-Compiler singleton** (avoids a data race from multiple States
	// concurrently writing a global hostState; -race friendly for V18).
	c.SetHostState(st)
	st.bridge.SetP3Compiler(c)
}
